[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/assets/:splat"
  status = 200

[[redirects]]
  from = "/onboard/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/onboard/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/onboard/:token/success"
  to = "https://banded-overcherished-darby.ngrok-free.dev/onboard/:token/success"
  status = 200
  force = true

[[redirects]]
  from = "/agency-api/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/agency/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/restrictions-api/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/restrictions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "https://banded-overcherished-darby.ngrok-free.dev/login"
  status = 200
  force = true
[[redirects]]
  from = "/email-accounts"
  to = "https://banded-overcherished-darby.ngrok-free.dev/accounts"
  status = 200
  force = true
[[redirects]]
  from = "/email-accounts/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/accounts/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/leads"
  to = "https://banded-overcherished-darby.ngrok-free.dev/lead_emails"
  status = 200
  force = true
[[redirects]]
  from = "/leads/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/lead_emails/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200